package com.elitec.com.infraestructure.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** ColorScheme Material3 mapeado a tokens ÁbacoPhy (web). */
fun abacoDarkColorScheme() = darkColorScheme(
    primary = AbacoColors.Cyan,
    onPrimary = AbacoColors.DarkBg,
    primaryContainer = AbacoColors.DarkSurfaceRaised,
    onPrimaryContainer = AbacoColors.Cyan,
    secondary = AbacoColors.Green,
    onSecondary = AbacoColors.DarkBg,
    secondaryContainer = AbacoColors.DarkSurfaceSoft,
    onSecondaryContainer = AbacoColors.Green,
    tertiary = AbacoColors.Purple,
    onTertiary = AbacoColors.DarkTextPrimary,
    background = AbacoColors.DarkBg,
    onBackground = AbacoColors.DarkTextPrimary,
    surface = AbacoColors.DarkSurface,
    onSurface = AbacoColors.DarkTextPrimary,
    surfaceVariant = AbacoColors.DarkSurfaceSoft,
    onSurfaceVariant = AbacoColors.DarkTextSecondary,
    outline = AbacoColors.DarkBorder,
    outlineVariant = AbacoColors.DarkSurfaceSoft,
    error = AbacoColors.Red,
    onError = AbacoColors.DarkTextPrimary,
    errorContainer = Color(0x33F17B7B),
    onErrorContainer = AbacoColors.Red,
    inverseSurface = AbacoColors.DarkTextPrimary,
    inverseOnSurface = AbacoColors.DarkBg,
    inversePrimary = AbacoColors.CyanDeep,
    surfaceBright = AbacoColors.DarkSurfaceRaised,
    surfaceDim = AbacoColors.DarkSidebar,
    surfaceContainer = AbacoColors.DarkSurface,
    surfaceContainerHigh = AbacoColors.DarkSurfaceRaised,
    surfaceContainerHighest = AbacoColors.DarkSurfaceSoft,
    surfaceContainerLow = AbacoColors.DarkSidebar,
    surfaceContainerLowest = AbacoColors.DarkBg,
)

fun abacoLightColorScheme() = lightColorScheme(
    primary = AbacoColors.CyanDeep,
    onPrimary = Color.White,
    primaryContainer = Color(0x1F1AA8A3),
    onPrimaryContainer = AbacoColors.CyanDeep,
    secondary = AbacoColors.GreenOk,
    onSecondary = Color.White,
    secondaryContainer = Color(0x1F3D9A2E),
    onSecondaryContainer = AbacoColors.GreenOk,
    tertiary = AbacoColors.Purple,
    onTertiary = Color.White,
    background = AbacoColors.LightBg,
    onBackground = AbacoColors.LightTextPrimary,
    surface = AbacoColors.LightSurface,
    onSurface = AbacoColors.LightTextPrimary,
    surfaceVariant = AbacoColors.LightSurfaceSoft,
    onSurfaceVariant = AbacoColors.LightTextSecondary,
    outline = AbacoColors.LightBorder,
    outlineVariant = AbacoColors.LightSurfaceSoft,
    error = AbacoColors.RedDanger,
    onError = Color.White,
    errorContainer = Color(0x33D64545),
    onErrorContainer = AbacoColors.RedDanger,
    inverseSurface = AbacoColors.LightTextPrimary,
    inverseOnSurface = AbacoColors.LightSurface,
    inversePrimary = AbacoColors.Cyan,
    surfaceContainer = AbacoColors.LightSurface,
    surfaceContainerHigh = AbacoColors.LightSurfaceRaised,
    surfaceContainerHighest = AbacoColors.LightSurfaceSoft,
    surfaceContainerLow = AbacoColors.LightBg,
    surfaceContainerLowest = Color.White,
)
