name = "abacophy-do"
main = "worker.js"
compatibility_date = "2024-09-01"

[[durable_objects.bindings]]
name = "ABACOPHY_STORE"
class_name = "AbacoPhyStore"

[[migrations]]
tag = "v1"
new_classes = ["AbacoPhyStore"]
