<script lang="ts">
import { onMount } from 'svelte'; import { Renderer, Program, Mesh, Triangle } from 'ogl';
type Props={timeSpeed?:number;warpFrequency?:number;warpSpeed?:number;warpAmplitude?:number;noiseScale?:number;grainAmount?:number;grainAnimated?:boolean;contrast?:number;gamma?:number;saturation?:number;zoom?:number;color1?:string;color2?:string;class?:string};
let {timeSpeed=.22,warpFrequency=5,warpSpeed=2,warpAmplitude=50,noiseScale=2,grainAmount=.08,grainAnimated=false,contrast=1.35,gamma=1,saturation=1,zoom=.9,color1='#61E6E1',color2='#B7F56A',class:className=''}:Props=$props();
let containerRef:HTMLDivElement;
const rgb=(hex:string):[number,number,number]=>{const m=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);return m?[parseInt(m[1],16)/255,parseInt(m[2],16)/255,parseInt(m[3],16)/255]:[1,1,1]};
onMount(()=>{const renderer=new Renderer({webgl:2,alpha:true,antialias:false,dpr:Math.min(devicePixelRatio||1,2)}),gl=renderer.gl,canvas=gl.canvas as HTMLCanvasElement;canvas.style.cssText='width:100%;height:100%;display:block';containerRef.appendChild(canvas);
const vertex='#version 300 es\nin vec2 position;void main(){gl_Position=vec4(position,0.,1.);}';
const fragment='#version 300 es\nprecision highp float;uniform vec2 iResolution;uniform float iTime,uTimeSpeed,uWarpFrequency,uWarpSpeed,uWarpAmplitude,uNoiseScale,uGrainAmount,uContrast,uGamma,uSaturation,uZoom;uniform vec3 uColor1,uColor2;out vec4 fragColor;mat2 Rot(float a){float s=sin(a),c=cos(a);return mat2(c,-s,s,c);}vec2 hash(vec2 p){p=vec2(dot(p,vec2(2127.1,81.17)),dot(p,vec2(1269.5,283.37)));return fract(sin(p)*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p),u=f*f*(3.-2.*f);return .5+.5*mix(mix(dot(-1.+2.*hash(i),f),dot(-1.+2.*hash(i+vec2(1,0)),f-vec2(1,0)),u.x),mix(dot(-1.+2.*hash(i+vec2(0,1)),f-vec2(0,1)),dot(-1.+2.*hash(i+vec2(1,1)),f-vec2(1)),u.x),u.y);}void main(){float t=iTime*uTimeSpeed;vec2 uv=gl_FragCoord.xy/iResolution.xy;float ratio=iResolution.x/iResolution.y;vec2 p=uv-.5;p/=max(uZoom,.001);float d=noise(vec2(t*.1,p.x*p.y)*uNoiseScale);p.y/=ratio;p*=Rot(radians((d-.5)*500.+180.));p.y*=ratio;p.x+=sin(p.y*uWarpFrequency+t*uWarpSpeed)/uWarpAmplitude;p.y+=sin(p.x*uWarpFrequency*1.5+t*uWarpSpeed)/(uWarpAmplitude*.5);float glow=smoothstep(-.7,.7,p.y*.9+p.x*.35);vec3 dark=vec3(.015,.025,.07);vec3 col=mix(dark,uColor2,smoothstep(-.45,.25,p.x));col=mix(col,uColor1,smoothstep(.15,.9,p.y+glow*.15));vec2 guv=uv*uNoiseScale+(uGrainAmount>0.0&&'+(grainAnimated?'true':'false')+'?vec2(iTime*.05):vec2(0));float grain=fract(sin(dot(guv,vec2(12.9898,78.233)))*43758.5453);col+=(grain-.5)*uGrainAmount;col=(col-.5)*uContrast+.5;float l=dot(col,vec3(.2126,.7152,.0722));col=mix(vec3(l),col,uSaturation);col=pow(max(col,0.),vec3(1./max(uGamma,.001)));fragColor=vec4(clamp(col,0.,1.),1.);}';
const program=new Program(gl,{vertex,fragment,uniforms:{iTime:{value:0},iResolution:{value:new Float32Array([1,1])},uTimeSpeed:{value:timeSpeed},uWarpFrequency:{value:warpFrequency},uWarpSpeed:{value:warpSpeed},uWarpAmplitude:{value:warpAmplitude},uNoiseScale:{value:noiseScale},uGrainAmount:{value:grainAmount},uContrast:{value:contrast},uGamma:{value:gamma},uSaturation:{value:saturation},uZoom:{value:zoom},uColor1:{value:new Float32Array(rgb(color1))},uColor2:{value:new Float32Array(rgb(color2))}}});
const mesh=new Mesh(gl,{geometry:new Triangle(gl),program}),resize=()=>{const r=containerRef.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height));const v=(program.uniforms.iResolution as any).value;v[0]=gl.drawingBufferWidth;v[1]=gl.drawingBufferHeight};const ro=new ResizeObserver(resize);ro.observe(containerRef);resize();let raf=0,t0=performance.now();const loop=(t:number)=>{(program.uniforms.iTime as any).value=(t-t0)*.001;renderer.render({scene:mesh});raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);ro.disconnect();canvas.remove()}});
</script><div bind:this={containerRef} class={"warp-background "+className} aria-hidden="true"></div><style>.warp-background{position:absolute;inset:0;width:100%;height:100%;overflow:hidden}</style>